name: Publish
on: 
  push:
    branches: [master]
jobs:
  gh-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install & Build
        run: |
          npm install
          npm run build
      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build